# -*- coding: utf-8 -*-
"""california_clusters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JaCbyxtokgdu3JwQgd_jKwcLIMJY3hHD
"""

import zipfile
from google.colab import drive

drive.mount('/content/drive/')

zip_ref = zipfile.ZipFile('/content/california_price.zip', 'r')
zip_ref.extractall()
zip_ref.close()

from sklearn.cluster import KMeans
import seaborn as sns
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np

df = pd.read_csv('/content/housing.csv')

df.head()

df = df.drop(["longitude", "latitude", "ocean_proximity"], axis=1)

df

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame)
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

le =  LabelEncoder()
for i in df:
    if df[i].dtype=='object':
        df[i] = le.fit_transform(df[i])
    else:
        continue

S=StandardScaler()

S.fit_transform(df)

model = KMeans

model=KMeans(n_clusters=5,random_state=6)
cluster=model.fit_predict(clean_dataset(df))

sns.scatterplot(x=df['median_house_value'],y=df['median_income'],hue=cluster)
plt.title("Clusters from California 1990s housing Dataset")
plt.show()